name: Lint and test
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y -qq build-essential git sqlite3 libtag-dev ffmpeg mpv
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=5m
      - name: Test
        run: go test ./...
